debug: true
server:
  port: 8080
spring:
  #
  # add appropriate configuraton to load the database here
  #
  sql:
    init:
      platform: postgresql
      mode: always

  #
  # Add standalone postgres datasource config here
  #
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://telenext-db.postgres.database.azure.com:5432/postgres?sslmode=require
    username: ${PGSQL_DB}
    password: ${PGSQL_PWD}
  #
  # Add the appropriate JPA config here
  #
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
