debug: true
server:
  port: 8080
spring:
  #
  # add appropriate configuraton to load the database here
  #
  sql:
  output:
    ansi:
      enabled: always

  #
  # Add standalone postgres datasource config here
  #
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres123
  #
  # Add the appropriate JPA config here
  #
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR